# https://dart.dev/guides/language/analysis-options
include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    # 41 cases to clean up
    lines_longer_than_80_chars: ignore
    # The example app explicitly takes a String of user-generated HTML and
    # inserts it straight into a <div> using innerHtml.
    unsafe_html: ignore

linter:
  rules:
    # https://github.com/dart-lang/linter/issues/574
    #- comment_references
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cancel_subscriptions
    - literal_only_boolean_expressions
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - package_api_docs
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - prefer_relative_imports
    - test_types_in_equals
    - unnecessary_await_in_return
    - unnecessary_raw_strings
    - use_if_null_to_convert_nulls_to_bools
    - use_raw_strings
    - use_string_buffers
    - use_super_parameters
