# https://dart.dev/tools/analysis
include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    # The example app explicitly takes a String of user-generated HTML and
    # inserts it straight into a <div> using innerHtml.
    unsafe_html: ignore
    # Waiting on a couple of bug fixes and new features before this should be enabled
    comment_references: ignore

linter:
  rules:
    # https://github.com/dart-lang/linter/issues/574
    #- comment_references
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cancel_subscriptions
    - literal_only_boolean_expressions
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - prefer_const_declarations
    - prefer_final_locals
    - prefer_final_in_for_each
    - unnecessary_await_in_return
    - unnecessary_raw_strings
    - use_if_null_to_convert_nulls_to_bools
    - use_raw_strings
    - use_string_buffers
