# Run against all markdown files in latest version of packages on pub.dev to
# see if any can provoke a crash

name: Crash Tests

on:
  schedule:
    # “At 00:00 (UTC) on Sunday.”
    - cron: '0 0 * * 0'

jobs:
  crash-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672
      - name: Install dependencies
        run: dart pub get
      - name: Run crash_test.dart
        run: dart test -P crash_test test/crash_test.dart
